version: '3.8'
services:
  redis:
    image: redis/redis-stack
    environment:
      - REDIS_ARGS = "--save 10 1 --appendonly yes"
    ports:
      - "127.0.0.1:6379:6379/tcp"
      - "127.0.0.1:8001:8001" # порт для керування та моніторингу через веб-інтерфейс
    volumes:
      - ./redis_data:/data:rw

# docker-compose -f docker-compose.yaml up --force-recreate
